# fly.toml app configuration file generated for furious-jokenpo on 2025-04-24T22:54:08-03:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "furious-jokenpo"
primary_region = "gig"
kill_signal = "SIGINT"
kill_timeout = "5s"

[experimental]
  auto_rollback = true

# [build] # Removido - Fly.io usará o Dockerfile automaticamente se presente na raiz

[env]
  PORT = "8080"

[[services]]
  protocol = "tcp"
  internal_port = 8080

  [[services.ports]]
    port = 80
    handlers = ["http"]

  [[services.ports]]
    port = 443
    handlers = ["tls", "http"]

  # Health check HTTP mais robusto
  [[services.http_checks]]
    interval = "10s"
    timeout = "2s"
    grace_period = "5s"
    method = "get"
    path = "/ping" # Aponta para a rota de health check da aplicação
    protocol = "http" # Verifica internamente via HTTP
    tls_skip_verify = true # Necessário para checks internos na rede Fly

[[vm]]
  memory = "1gb"
  cpu_kind = "shared"
  cpus = 1
