app = "furious-jokenpo"
primary_region = "gru"
kill_signal = "SIGINT"
kill_timeout = "5s"

[experimental]
auto_rollback = true

[env]
PORT = "8080"
FLASK_ENV = "production"
GUNICORN_CMD_ARGS = "--workers=2 --threads=4 --timeout=0"

[[services]]
protocol = "tcp"
internal_port = 8080

  [[services.ports]]
  port = 80
  handlers = ["http"]

  [[services.ports]]
  port = 443
  handlers = ["tls", "http"]

  [[services.http_checks]]
  interval = "10s"
  timeout = "5s"
  grace_period = "5s"
  method = "get"
  path = "/ping"
  protocol = "http"
  tls_skip_verify = true

[[vm]]
memory = "1gb"
cpu_kind = "shared"
cpus = 1