app = "furious-jokenpo"
primary_region = "gru"
kill_signal = "SIGINT"
kill_timeout = "30s"

[experimental]
auto_rollback = true

[deploy]
strategy = "rolling"

[env]
PORT = "8080"
FLASK_ENV = "production"
GUNICORN_CMD_ARGS = "--workers=2 --threads=4 --timeout=60"

[[services]]
protocol = "tcp"
internal_port = 8080
auto_stop_machines = true
auto_start_machines = true
min_machines_running = 1

  [[services.ports]]
  port = 80
  handlers = ["http"]

  [[services.ports]]
  port = 443
  handlers = ["tls", "http"]

  [[services.http_checks]]
  interval = "45s"
  timeout = "15s"
  grace_period = "60s"
  method = "get"
  path = "/ping"
  protocol = "http"
  tls_skip_verify = true
  [services.http_checks.headers]
    X-Forwarded-Proto = "https"

[[vm]]
memory = "1gb"
cpu_kind = "shared"
cpus = 1

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

[[statics]]
  guest_path = "/app/static"
  url_prefix = "/static"
